// Faculty Data for SRKREC CSD-CSIT Department
// Updated with verified official photo downloads in assets/faculty_official/

const facultyData = [
    // --- CSD FACULTY MEMBERS (1 - 9) ---
    {
        id: 1,
        name: "Dr. Suresh Babu Mudunuri",
        designation: "Professor & Head of Department",
        department: "CSD",
        category: ["hod", "csd", "professor"],
        photo: "assets/faculty_official/csd_780.jpeg",
        email: "suresh.mudunuri@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "20+ Years",
        qualification: "Ph.D in Computer Science",
        specialization: "AI, Machine Learning & Cloud",
        about: "Dr. Suresh Babu Mudunuri is Professor and Head of Department of Computer Science & Design (CSD) at SRKR Engineering College. With over two decades of research and academic excellence, he leads strategic initiatives in AI, ML, and Cloud Infrastructure.",
        education: [
            { degree: "Ph.D in Computer Science", institution: "JNTU", year: "2010" },
            { degree: "M.Tech in CSE", institution: "JNTU", year: "2002" }
        ],
        research: ["Artificial Intelligence", "Machine Learning", "Cloud Computing"],
        publications: [
            { title: "AI-Driven Cloud Optimization Frameworks", journal: "IEEE Access", year: "2023" }
        ],
        subjects: ["Machine Learning", "Cloud Computing", "Artificial Intelligence"],
        achievements: [
            { icon: "🏆", text: "Head of Department - CSD" },
            { icon: "📚", text: "35+ Research Publications" }
        ],
        stats: { experience: "20+", publications: "35+", projects: "15+", students: "450+" }
    },
    {
        id: 2,
        name: "A. Aswini Priyanka",
        designation: "Assistant Professor",
        department: "CSD",
        category: ["csd", "assistant-professor"],
        photo: "assets/faculty_official/csd_1339.jpg",
        email: "aapriyanka@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "8+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Cloud Computing",
        about: "A. Aswini Priyanka is an Assistant Professor in the CSD department specializing in Cloud Computing, virtualized systems, and distributed cloud architectures.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2015" }],
        research: ["Cloud Computing", "Distributed Systems"],
        publications: [{ title: "Scalable Cloud Resource Allocation", journal: "IJCS", year: "2022" }],
        subjects: ["Cloud Computing", "Web Technologies"],
        achievements: [{ icon: "🎓", text: "Cloud Certified Educator" }],
        stats: { experience: "8+", publications: "10+", projects: "8+", students: "300+" }
    },
    {
        id: 3,
        name: "S. Mohan Krishna",
        designation: "Assistant Professor",
        department: "CSD",
        category: ["csd", "assistant-professor"],
        photo: "assets/faculty_official/csd_1376.jpeg",
        email: "mohanakrishna.seerla@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "7+ Years",
        qualification: "M.Tech in CSE",
        specialization: "AI & ML",
        about: "S. Mohan Krishna specializes in Artificial Intelligence and Machine Learning applications, focusing on deep neural network architectures and computer vision.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2016" }],
        research: ["Machine Learning", "Deep Learning", "AI"],
        publications: [{ title: "Neural Networks in Pattern Recognition", journal: "IEEE", year: "2022" }],
        subjects: ["Artificial Intelligence", "Machine Learning"],
        achievements: [{ icon: "💡", text: "AI & ML Research Mentor" }],
        stats: { experience: "7+", publications: "8+", projects: "6+", students: "280+" }
    },
    {
        id: 4,
        name: "P S V SURYA KUMAR",
        designation: "Assistant Professor",
        department: "CSD",
        category: ["csd", "assistant-professor"],
        photo: "assets/faculty_official/csd_1382.jpg",
        email: "psvsuryakumar@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "6+ Years",
        qualification: "M.Tech in CSE",
        specialization: "IoT (Internet of Things)",
        about: "P S V SURYA KUMAR is an Assistant Professor specializing in Internet of Things (IoT), smart embedded sensors, and real-time edge computing networks.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2017" }],
        research: ["Internet of Things", "Embedded Systems"],
        publications: [{ title: "IoT Sensor Node Energy Efficiency", journal: "Springer", year: "2021" }],
        subjects: ["IoT Architecture", "Embedded Systems"],
        achievements: [{ icon: "⚡", text: "IoT Hardware Lab Director" }],
        stats: { experience: "6+", publications: "7+", projects: "10+", students: "250+" }
    },
    {
        id: 5,
        name: "ANGARA SATYAM",
        designation: "Assistant Professor",
        department: "CSD",
        category: ["csd", "assistant-professor"],
        photo: "assets/faculty_official/csd_1472.jpg",
        email: "asatyam@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "7+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Artificial Intelligence",
        about: "ANGARA SATYAM focuses on Artificial Intelligence algorithms, expert systems, and intelligent automation frameworks in modern software design.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2016" }],
        research: ["Artificial Intelligence", "Intelligent Systems"],
        publications: [{ title: "Automated Decision Support Systems", journal: "IJAI", year: "2022" }],
        subjects: ["Artificial Intelligence", "Python"],
        achievements: [{ icon: "🤖", text: "AI Coding Contest Coach" }],
        stats: { experience: "7+", publications: "6+", projects: "5+", students: "260+" }
    },
    {
        id: 6,
        name: "Dr. K. Srinivasa Rao",
        designation: "Assistant Professor",
        department: "CSD",
        category: ["csd", "assistant-professor"],
        photo: "assets/faculty_official/csd_1474.jpg",
        email: "ksrinivasarao@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "10+ Years",
        qualification: "Ph.D in Computer Science",
        specialization: "Computer Networks & Security",
        about: "Dr. K. Srinivasa Rao holds a Ph.D in Computer Science. His academic interests encompass computer networking protocols, wireless sensor networks, and data security.",
        education: [{ degree: "Ph.D in Computer Science", institution: "Andhra University", year: "2018" }],
        research: ["Computer Networks", "Cyber Security"],
        publications: [{ title: "Routing Protocols in Ad-Hoc Networks", journal: "Elsevier", year: "2021" }],
        subjects: ["Computer Networks", "Information Security"],
        achievements: [{ icon: "📜", text: "Ph.D Doctorate Holder" }],
        stats: { experience: "10+", publications: "15+", projects: "12+", students: "400+" }
    },
    {
        id: 7,
        name: "K. Bhanu Rajesh Naidu",
        designation: "Assistant Professor",
        department: "CSD",
        category: ["csd", "assistant-professor"],
        photo: "assets/faculty_official/csd_1479.jpg",
        email: "kbrnaidu@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "6+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Cloud Computing",
        about: "K. Bhanu Rajesh Naidu is an Assistant Professor specializing in Cloud Computing, DevOps automation pipelines, and containerized cloud applications.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2017" }],
        research: ["Cloud Infrastructure", "DevOps"],
        publications: [{ title: "DevOps Integration in Cloud DevOps", journal: "IEEE", year: "2022" }],
        subjects: ["Cloud Computing", "DevOps Systems"],
        achievements: [{ icon: "☁️", text: "AWS Certified Solution Architect" }],
        stats: { experience: "6+", publications: "5+", projects: "8+", students: "220+" }
    },
    {
        id: 8,
        name: "N. Aneela",
        designation: "Assistant Professor",
        department: "CSD",
        category: ["csd", "assistant-professor"],
        photo: "assets/faculty_official/csd_1483.jpg",
        email: "aneela@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "5+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Machine Learning",
        about: "N. Aneela is an Assistant Professor focusing on Machine Learning algorithms, predictive analytics, and natural language processing models.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2018" }],
        research: ["Machine Learning", "Natural Language Processing"],
        publications: [{ title: "Predictive Analytics in Data Science", journal: "IJML", year: "2023" }],
        subjects: ["Machine Learning", "Data Mining"],
        achievements: [{ icon: "📊", text: "Data Science Mentor" }],
        stats: { experience: "5+", publications: "6+", projects: "4+", students: "200+" }
    },
    {
        id: 9,
        name: "M Sai Madhuri",
        designation: "Teaching Assistant",
        department: "CSD",
        category: ["csd", "teaching-assistant"],
        photo: "assets/faculty_official/csd_1504.jpeg",
        email: "madhuryamudundi@gmail.com",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "3+ Years",
        qualification: "B.Tech / M.Tech in CSE",
        specialization: "Machine Learning",
        about: "M Sai Madhuri serves as a Teaching Assistant assisting in undergraduate laboratory sessions for Machine Learning and Programming Fundamentals.",
        education: [{ degree: "M.Tech in CSE", institution: "SRKR", year: "2021" }],
        research: ["Machine Learning", "Python Programming"],
        publications: [{ title: "Lab Assistance Methods in ML", journal: "JED", year: "2022" }],
        subjects: ["Machine Learning Lab", "Python Lab"],
        achievements: [{ icon: "💻", text: "Lab Coordinator" }],
        stats: { experience: "3+", publications: "2+", projects: "3+", students: "150+" }
    },

    // --- CSIT FACULTY MEMBERS (10 - 19) ---
    {
        id: 10,
        name: "DR NGK MURTHY",
        designation: "Professor & Head of Department",
        department: "CSIT",
        category: ["hod", "csit", "professor"],
        photo: "assets/faculty_official/csit_781.jpeg",
        email: "gopinukala@gmail.com",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "18+ Years",
        qualification: "Ph.D in Information Technology",
        specialization: "Information Technology & Systems",
        about: "DR NGK MURTHY is Professor and Head of Department of CSIT at SRKR Engineering College. With over 18 years of academic leadership, he drives advanced research in enterprise IT architectures and data networks.",
        education: [
            { degree: "Ph.D in IT", institution: "JNTU", year: "2011" },
            { degree: "M.Tech in IT", institution: "JNTU", year: "2003" }
        ],
        research: ["Information Technology", "Enterprise Data Networks"],
        publications: [{ title: "Enterprise IT Security Architecture", journal: "Springer", year: "2022" }],
        subjects: ["Information Technology", "Network Security"],
        achievements: [
            { icon: "🏆", text: "Head of Department - CSIT" },
            { icon: "📚", text: "30+ Research Publications" }
        ],
        stats: { experience: "18+", publications: "30+", projects: "18+", students: "420+" }
    },
    {
        id: 11,
        name: "N. NAVYA",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1259.jpg",
        email: "navyanallaparaju@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "6+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Machine Learning",
        about: "N. NAVYA is an Assistant Professor in CSIT specializing in Machine Learning algorithms, predictive analytics, and computer vision classification.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2017" }],
        research: ["Machine Learning", "Data Mining"],
        publications: [{ title: "Deep Learning for Visual Analytics", journal: "IEEE", year: "2022" }],
        subjects: ["Machine Learning", "Data Structures"],
        achievements: [{ icon: "🌟", text: "Active Research Scholar" }],
        stats: { experience: "6+", publications: "7+", projects: "5+", students: "230+" }
    },
    {
        id: 12,
        name: "NETI PRAVEEN",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1348.jpg",
        email: "npraveen@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "7+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Machine Learning",
        about: "NETI PRAVEEN is an Assistant Professor in CSIT specializing in Machine Learning models, data analytics, and computational intelligence.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2016" }],
        research: ["Machine Learning", "Intelligent Systems"],
        publications: [{ title: "Classification Models in Medical Imaging", journal: "IJCS", year: "2021" }],
        subjects: ["Machine Learning", "Database Management"],
        achievements: [{ icon: "🎯", text: "Student Project Coordinator" }],
        stats: { experience: "7+", publications: "8+", projects: "7+", students: "270+" }
    },
    {
        id: 13,
        name: "K V SUNIL VARMA",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1372.jpg",
        email: "kvsunilvarma@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "6+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Machine Learning",
        about: "K V SUNIL VARMA focuses on Machine Learning algorithms, statistical data analysis, and software engineering methodologies.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2017" }],
        research: ["Machine Learning", "Software Engineering"],
        publications: [{ title: "Statistical ML Models for Big Data", journal: "Springer", year: "2022" }],
        subjects: ["Machine Learning", "Software Engineering"],
        achievements: [{ icon: "🛠️", text: "Software Systems Mentor" }],
        stats: { experience: "6+", publications: "6+", projects: "6+", students: "240+" }
    },
    {
        id: 14,
        name: "P MOUNA",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1398.jpeg",
        email: "mouna.p@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "5+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Machine Learning",
        about: "P MOUNA is an Assistant Professor specializing in Machine Learning, pattern recognition, and neural network optimization techniques.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2018" }],
        research: ["Machine Learning", "Neural Networks"],
        publications: [{ title: "Neural Network Optimization", journal: "IJCA", year: "2023" }],
        subjects: ["Machine Learning", "Object Oriented Programming"],
        achievements: [{ icon: "💡", text: "Innovative Teaching Award" }],
        stats: { experience: "5+", publications: "5+", projects: "4+", students: "210+" }
    },
    {
        id: 15,
        name: "P MANOJ",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1399.jpeg",
        email: "manoj.p@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "5+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Prompt Engineering & Generative AI",
        about: "P MANOJ specializes in Prompt Engineering, Generative AI models, Large Language Model fine-tuning, and modern AI application development.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2018" }],
        research: ["Prompt Engineering", "Generative AI", "LLMs"],
        publications: [{ title: "Prompt Engineering Patterns for LLMs", journal: "IEEE", year: "2023" }],
        subjects: ["Prompt Engineering", "Generative AI", "Python"],
        achievements: [{ icon: "🤖", text: "Generative AI Workshop Lead" }],
        stats: { experience: "5+", publications: "6+", projects: "8+", students: "250+" }
    },
    {
        id: 16,
        name: "ANUSURI KRISHNA VENI",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1478.jpg",
        email: "akveni@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "6+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Machine Learning",
        about: "ANUSURI KRISHNA VENI is an Assistant Professor specializing in Machine Learning, data mining algorithms, and predictive modeling.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2017" }],
        research: ["Machine Learning", "Data Mining"],
        publications: [{ title: "Data Mining Techniques in Healthcare", journal: "IJCS", year: "2022" }],
        subjects: ["Machine Learning", "Data Structures"],
        achievements: [{ icon: "📊", text: "Academic Excellence Mentor" }],
        stats: { experience: "6+", publications: "6+", projects: "5+", students: "230+" }
    },
    {
        id: 17,
        name: "K V V Satya Trinadh Naidu",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1480.jpg",
        email: "kvvstnaidu@srkrec.ac.in",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "7+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Cyber Security, Java, Python",
        about: "K V V Satya Trinadh Naidu specializes in Cyber Security protocols, ethical hacking, enterprise Java development, and Python application development.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2016" }],
        research: ["Cyber Security", "Secure Coding Practices", "Python"],
        publications: [{ title: "Vulnerability Assessments in Modern Web Apps", journal: "Springer", year: "2022" }],
        subjects: ["Cyber Security", "Java Programming", "Python"],
        achievements: [{ icon: "🛡️", text: "Cyber Security Lead Advisor" }],
        stats: { experience: "7+", publications: "8+", projects: "9+", students: "310+" }
    },
    {
        id: 18,
        name: "D Parvathi",
        designation: "Assistant Professor",
        department: "CSIT",
        category: ["csit", "assistant-professor"],
        photo: "assets/faculty_official/csit_1503.jpeg",
        email: "parvathiram21@gmail.com",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "5+ Years",
        qualification: "M.Tech in CSE",
        specialization: "Machine Learning",
        about: "D Parvathi is an Assistant Professor focusing on Machine Learning algorithms, statistical pattern recognition, and data analytics.",
        education: [{ degree: "M.Tech in CSE", institution: "JNTUK", year: "2018" }],
        research: ["Machine Learning", "Pattern Recognition"],
        publications: [{ title: "Pattern Recognition in Complex Datasets", journal: "IJML", year: "2023" }],
        subjects: ["Machine Learning", "C Programming"],
        achievements: [{ icon: "📚", text: "Faculty Publication Award" }],
        stats: { experience: "5+", publications: "5+", projects: "4+", students: "200+" }
    },
    {
        id: 19,
        name: "K Sri Vigyna",
        designation: "Teaching Assistant",
        department: "CSIT",
        category: ["csit", "teaching-assistant"],
        photo: "assets/faculty_official/csit_1509.jpeg",
        email: "vignyak@gmail.com",
        linkedin: "#",
        scholar: "#",
        profile: "#",
        experience: "3+ Years",
        qualification: "B.Tech / M.Tech in CSE",
        specialization: "Machine Learning",
        about: "K Sri Vigyna serves as a Teaching Assistant assisting students in Machine Learning and Python practical laboratory courses.",
        education: [{ degree: "M.Tech in CSE", institution: "SRKR", year: "2021" }],
        research: ["Machine Learning", "Python Programming"],
        publications: [{ title: "Practical ML Lab Methodologies", journal: "JED", year: "2022" }],
        subjects: ["Machine Learning Lab", "Python Lab"],
        achievements: [{ icon: "💻", text: "Practical Lab Facilitator" }],
        stats: { experience: "3+", publications: "2+", projects: "3+", students: "160+" }
    }
];
